package srcfile

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsTest(t *testing.T) {
	if !IsTest("backend/internal/handler/labels_test.go") {
		t.Error("labels_test.go should be a test file")
	}
	if IsTest("backend/internal/handler/labels.go") {
		t.Error("labels.go is not a test file")
	}
}

func TestIsGenerated(t *testing.T) {
	dir := t.TempDir()
	gen := filepath.Join(dir, "mocks.go")
	os.WriteFile(gen, []byte("// Code generated by MockGen. DO NOT EDIT.\npackage mock\n"), 0o644)
	hand := filepath.Join(dir, "real.go")
	os.WriteFile(hand, []byte("// Package real does things.\npackage real\n"), 0o644)

	cache := map[string]bool{}
	if !IsGenerated(gen, cache) {
		t.Error("mocks.go should be generated")
	}
	if IsGenerated(hand, cache) {
		t.Error("real.go should not be generated")
	}
	// memoized
	if !cache[gen] || cache[hand] {
		t.Error("cache not populated as expected")
	}
}
